language: node_js

node_js:
  - 7

branches:
  only:
  - niall

notifications:
  webhooks: {
  "urls": [
  "http://9.80.98.169/travis/notifications"
 ],
 "on_success": "always",
 "on_failure": "always",
 "on_start": "always"
}
