language: node_js

node_js:
  - 7

branches:
  only:
  - niall

notifications:
  webhooks: {
    urls: "http://ikhnaton.rtp.raleigh.ibm.com:8000/travis/notifications",
    on_success: "always",
    on_failure: "always",
    on_start: "always"
}
